name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend
    
    - name: Build application
      run: wails build -clean -platform windows/amd64 -ldflags "-H windowsgui"
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.tag }}
        name: Release ${{ github.event.inputs.tag }}
        body: |
          ## Windows Service Manager ${{ github.event.inputs.tag }}
          
          现代化的 Windows 后台服务管理工具
          
          ### 使用说明
          1. 下载并运行 `services.exe`
          2. 点击"添加服务"创建新的后台服务
          3. 请以管理员权限运行
          
        artifacts: "build/bin/services.exe"
        artifactContentType: "application/octet-stream"
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}